language: erlang
otp_release:
  - 17.3
script:
  - rebar get-deps
  - rebar compile
  - rebar eunit -r skip_deps=true
  - rebar ct -r skip_deps=true
  - rebar generate
after_success:
  - mkdir s3
  - tar -cz -C release -f s3/build-$TRAVIS_BUILD_NUMBER.tar.gz .
before_deploy:
  - tar -cz -C release -f release-$TRAVIS_TAG.tar.gz .
deploy:
  - provider: s3
    access_key_id:
      secure: "eekUQdZzNHN0k/l66fMxaHw8yNOABhPN3SxLCkRqfFY8pstYZrkwmPvK9DiV2afB0gJaCSAQWBFi1Xtg2roACvFsBaYTdGNltNkv62xwOvmX4OARMctsYs9VOmldKkl7hD7yrrqdVkhVndR/PCMkLK6BeJXtzZ57qrCBtnyOcYU="
    secret_access_key:
      secure: "lJLpBSqVOZKS5xZ8gr89mDJLJs9njSKK84ccWMZB3tLEjw0k4MDPID9HkSdvoIFCW5aYpJPzKt4TPMyQaRVFRqGFZPUhDagxarywMUju7lQib+HjSWQqgYP0V7xDt+xDS+cs7TsiI1EQt3JZDPAGMTof7ZFXurXKdAATpPryvVk="
    bucket: "erb-archive"
    local_dir: s3
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api-key: "0d535a33af860566d27785f3de57fceba6422e38"
    file: "release-$TRAVIS_TAG.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
