language: erlang
otp_release:
  - 17.3
script:
  - rebar get-deps
  - rebar compile
  - rebar eunit -r skip_deps=true
  - rebar ct -r skip_deps=true
  - rebar generate
after_success:
  - tar -cz -C release -f build-$TRAVIS_BUILD_NUMBER.tar.gz .
before_deploy:
  - tar -cz -C release -f release-$TRAVIS_TAG.tar.gz .
deploy:
  - provider: s3
    access_key_id: "AKIAIJKIG6WU72556DHQ"
    secret_access_key: "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"
    bucket: "erb-archive"
    file: "release-$TRAVIS_BUILD_NUMBER.tar.gz"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: releases
    api-key: "0d535a33af860566d27785f3de57fceba6422e38"
    file: "release-$TRAVIS_TAG.tar.gz"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
