language: erlang
otp_release:
  - 17.3
install:
  - cd rebar
  - ./bootstrap
  - cd ..
script:
  - rebar/rebar get-deps
  - rebar/rebar compile
  - rebar/rebar eunit skip_deps=true
  - rebar/rebar ct skip_deps=true
  - rebar/rebar generate
  - cd release
  - tar -cz -f ../release-$TRAVIS_BUILD_NUMBER.tar.gz *
  - cd ..
deploy:
  provider: releases
  api-key: "0d535a33af860566d27785f3de57fceba6422e38"
  file: "release-$TRAVIS_BUILD_NUMBER.tar.gz"
  skip_cleanup: true